server:
  port: 9001
  servlet:
    context-path: /client

spring:
  application:
    name: sso-client-demo

# SSO 配置
sso:
  # 认证服务器地址
  auth-url: http://localhost:8000/api/sso/auth
  # 单点注销地址
  logout-url: http://localhost:8000/api/sso/logout
  # 用户信息获取地址
  userinfo-url: http://localhost:8000/api/sso/userinfo
  # JWT token有效期（秒）
  token-timeout: 43200